import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/Components/Navbar/Navbar";
import Sidebar from "@/Components/Sidebar/Sidebar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Brogrammers",
  description: "Generated by HAMN",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Navbar - Fixed at the top */}
        <div className="fixed top-0 left-0 w-full z-50">
          <Navbar />
        </div>

        <div className="flex">
          {/* Sidebar - Fixed on the left */}
          <div className="fixed top-16 left-0 w-64 h-full bg-gray-100 shadow-md">
            <Sidebar />
          </div>

          {/* Main Content - Adjust margin for sidebar */}
          <div className="flex-1 ml-64 pt-16">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}